name: Main-Test

on: 
  push:
    branches:
      - master

jobs:
  Test-Master:
    uses: ./.github/workflows/test-call-workflow.yml
    with: 
      environment: 'Testy'
  Test-Master2:
    uses: ./.github/workflows/test-call-workflow.yml
    with: 
      environment: 'Dev'
  Test-Master3:
    if: |-
      ${{ github.ref != 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'pull_request') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
  Test-Master4:
    if: |-
      ${{ github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'pull_request') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"