name: Nginx-Image-Push-Master

on: 
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master

jobs:
  Image-Build-Scan-Push:
    if: |-
      ${{ github.ref == 'refs/heads/main' || startsWith( github.ref, "refs/tags/v" ) }}
    environment: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: edar822/thetrinity:latest
          platforms: linux/amd64,linux/arm64