name: Live-Smoke-Test

on: push
  # push:
    # branches:
    #   - master

jobs:
  Cypress-SmokeTest:
    environment: Production
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: "Checkout Code ☁️"
        uses: actions/checkout@v2
      - name: "Run Smoke Tests with Cypress 🔎"
        # run: cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: e2e
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}