name: Teardown test

on:
  pull_request:
    types: [ closed ]

jobs:
  PR-Merge:
    if: ${{ github.ref != 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Retrieve name"
        id: setname
        run: |
          echo $GITHUB_HEAD_REF
          slotname=${GITHUB_REF_NAME//['/']/-}
          echo "The slot name is ${slotname}"